/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.edu.pk.student.tomaszkisiel.jmb.preview;

import org.junit.Test;
import pl.edu.pk.student.tomaszkisiel.jmb.preview.mailing.MailingMicroservice;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        MailingMicroservice classUnderTest = new MailingMicroservice();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
