/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.edu.pk.student.tomaszkisiel.jmb.preview.pubsub;

import pl.edu.pk.student.tomaszkisiel.jmb.JmbServer;

public class PubSubMicroservice {
    private final static int PORT = 3000;

    public static void main(String[] args) {
        new JmbServer().run(PORT);
    }
}
